apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: hello-world-app
description: Hello World Deployment Pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
 - targetId: qsprod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/fair-feat-379308/locations/us-central1/clusters/quickstart-cluster-qsdev
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsprod
description: production cluster
gke:
 cluster: projects/fair-feat-379308/locations/us-central1/clusters/quickstart-cluster-qsprod
