steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/fair-feat-379308/quickstart-docker-repo/webserver:1.0.6', '.' ]
images:
- 'us-central1-docker.pkg.dev/fair-feat-379308/quickstart-docker-repo/webserver:1.0.6'

- name: 'gcr.io/cloud-builders/gke-deploy'
- 'apply'
- '--filename=k8s/*'
- '--cluster=quickstart-cluster-qsdev'
- '--location=us-central1'
images:
- 'us-central1-docker.pkg.dev/fair-feat-379308/quickstart-docker-repo/webserver:1.0.6'
